// <auto-generated />
namespace OERS.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Item_Notes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Item_Notes));
        
        string IMigrationMetadata.Id
        {
            get { return "201609060037507_Item_Notes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
