// <auto-generated />
namespace TRLAFCoSys.Queries.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBeginningVolumeOnMilkDelivUtilizRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBeginningVolumeOnMilkDelivUtilizRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201911151408413_AddBeginningVolumeOnMilkDelivUtilizRecord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
